# pubspec.yaml (FINAL PATHS)

name: gamerz_adda
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ZAROORI PACKAGES
  http: ^1.1.0
  video_player: ^2.8.1
  razorpay_flutter: ^1.3.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# --- YAHAN PAR ASSETS DECLARATION AAYEGA ---
flutter:
  uses-material-design: true

  # SAHI PATHS (Ab files lib/assets/ ke andar hain)
  assets:
    # Poora assets folder declare karein
    - lib/assets/
