# main.yml (Corrected Code)

name: Flutter Build APK

on:
  push:
    branches:
      - main # main branch par push hone par chalao

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          # Yahan woh version likhein jo aapki 'pubspec.yaml' ke 'environment' mein hai
          flutter-version: '3.16.5' 

      - name: Get packages
        run: flutter pub get

      - name: Build APK (RELEASE)
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Notify on completion (Optional)
        run: echo "Build complete! Check the 'Actions' tab for the APK."
