name: Flutter Build APK

on:
  push:
    branches:
      - main # Yahan 'main' branch ka naam hai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          # Aapke Flutter environment ke liye zaroori version
          flutter-version: '3.16.5' 

      - name: Get packages
        run: flutter pub get

      - name: Build APK (RELEASE)
        run: flutter build apk --release

      - name: Upload artifact
        # ZAROORI FIX: V3 ko V4 se badal diya gaya hai
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Notify on completion
        run: echo "Build complete! Check the 'Actions' tab for the APK."
